"""empty message

Revision ID: 4fc9bb5517e5
Revises: 57705e82a593
Create Date: 2023-01-12 19:18:05.320205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc9bb5517e5'
down_revision = '57705e82a593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegram_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegram_code', schema=None) as batch_op:
        batch_op.drop_column('created')

    # ### end Alembic commands ###
